apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
      - name: quotes
        image: docker-username/quotes
        imagePullPolicy: Always
        ports:
        - containerPort: 8000